### ISSUE TITLE
Implement media position

### ISSUE THREAD

**Issue by lindsaymarkward** [calmor15014/HA-Component-mythtv-frontend#11]
GetStatus reports the current and total time - use this to indicate position of playback

**Comment by lindsaymarkward** [comment]
Hi @calmor15014 - I've implemented some functions for media position, and now the UI shows the position playbar, but it's not accurate. I'm not sure what I'm missing, as the values are correct (duration and position times are the correct seconds, shown in the HA log output).
Perhaps you could have a look and see. I'll keep trying too.
https://github.com/lindsaymarkward/HA-Component-mythtv-frontend/tree/add_media_details

**Comment by calmor15014** [comment]
I'll pull your code this weekend and try to test it. I don't know if maybe
you have to cast the xml string values to float or int; I got stuck there
with the check to see if volume was muted and comparing 0 to '0'.

Just curious (again since I'm new with GitHub), why your own fork and not
just a new branch off of master? I'm good either way, but didn't know if
one held more benefits.

**Comment by lindsaymarkward** [comment]
I'll try casting the values - good idea. They look right in the log, and it almost works, so I didn't think about that.
I forked your repo before you added me as a collaborator when I couldn't have pushed to yours.

**Comment by lindsaymarkward** [comment]
And that was it! Thanks for the tip.

**Comment by calmor15014** [comment]
No problem! Glad that worked and that I could be of some assistance.

I'll merge shortly and pull probably tomorrow to test it out.

Jim

**Comment by calmor15014** [comment]
Tested on my dev container and seems to work well.  The position play bar in HA is subtle but seems to be an accurate reflection of what MythTV reports.  Great work!
