### ISSUE TITLE
Keep up with changes to mythtv_services_api

### ISSUE THREAD

**Issue by lindsaymarkward** [calmor15014/HA-Component-mythtv-frontend#14]
The services API is being updated as we develop this. How should we keep up?
1. We can update the platform to use the latest GitHub commit and version number (as of now, this has moved on from the version referred to by our code). I noticed this seems to install it each time you run `hass`.
2.Just expect it to be available and install using pip in the virtual environment. This is not automatic, but shouldn't re-download/install each time.
When we submit/release the platform, we can pin it to a certain API version, which might be on PyPI by then.

**Comment by calmor15014** [comment]
I saw that it did hit 0.0.4 before my PR for the timeout, and is now at 0.0.5. I don't expect the API to experience any failure of backwards compatibility, but that doesn't mean it won't happen. 

I think while we develop we could do either of those two - I actually kind of like the re-download but could see why it might not be the best choice. It's probably why local testing of the timeout script didn't work, because my changes were overwritten. It does greatly simplify the script for beta testing, but seems like it could cause an issue if the repository is unavailable during the launch of hass.

I suppose option #2 is the best for now?

**Comment by lindsaymarkward** [comment]
Good, let's go with 2 (btw #2 is issue 2 :)
Now that Bill has made it installable with pip, that'll be easy enough. 
Personally, when I'm testing, I run it several times - one for each change/test - so I don't want to wait for the library to install. I think I can do this now and submit a PR that closes this issue.

**Comment by calmor15014** [comment]
I wondered why it linked. I'll figure this thing out yet!
