### ISSUE TITLE
Since Upgrading to 0.92.1 now getting config check errors

### ISSUE THREAD

**Issue by RXM307** [calmor15014/HA-Component-mythtv-frontend#33]
Since Upgrading to 0.92.1 (maybe from 0.91.2 I think) now getting config check errors, still appears to work but it is rather annoying....

2019-05-01 21:55:20 ERROR (MainThread) [homeassistant.components.homeassistant] Integration mythtv not found when trying to verify its media_player platform.

**Comment by calmor15014** [comment]
It looks like since 0.92, a new `manifest.json` file is required to be with every component.  Native / official components would have likely been automatically added when they made the breaking change, but since this is not an "official" component yet for a few reasons, it doesn't yet have one.  Even though the docs say it doesn't pertain to custom components, there are a number of complaints on the HA forums about this issue.

[Developer Docs for integration](https://developers.home-assistant.io/docs/en/creating_integration_manifest.html)

Woogrk is still crushing my will to live (and taking my dev time).  It doesn't impact anything for function, but will definitely load the logfile.  I suspect that in a later version it will be an absolute requirement, so it's marked as a bug and needs addressed.

**Comment by RXM307** [comment]
Thanks For That I've created Pull Request #34 to add a Basic Manifest.json which seems fixes the immediate problem but may need additional info going forward.

**Comment by gmschade** [comment]
added pull request [#](https://github.com/calmor15014/HA-Component-mythtv-frontend/pull/36) also edited media_player.py to match the homeassistant wake_on_lan component

**Comment by RXM307** [comment]
@gmschade have you tried restarting Homeassistant, Mine was failing after adding the manifest.json

**Comment by gmschade** [comment]
> @gmschade have you tried restarting Home assistant, Mine was failing after adding the manifest.json
> 
> No errors but web gui was not available, seemed to hang on Loading....

I had the same problem too at first, I ended up tracking wakeonlan to the same version that homeassistant uses. Had to do some rewrite of media_player.py to work with the newer version of wakeonlan. and using manifest.json for the require.

the media_player.py and the manifest.json submitted the pull request for work fine together, for me

**Comment by lindsaymarkward** [comment]
This should be fixed by the latest merge from PR #36 
(Reopen if it's not.)
