### ISSUE TITLE
Update for MediaPlayerEntity

### ISSUE THREAD

**Issue by lindsaymarkward** [calmor15014/HA-Component-mythtv-frontend#38]
As of Home Assistant 0.110:
"MediaPlayerDevice is deprecated, modify MythTVFrontendDevice to extend MediaPlayerEntity"

**Comment by calmor15014** [comment]
It's been a while, mate.  Looks like it's time for me to update HA again and start testing.

**Comment by calmor15014** [comment]
I dug into that message.  It isn't going to hurt things any time soon, but since it's a quick fix I'll try to clean it up this week.  But, considering I just upgraded python to 3.8.3 on the test container and the development machine... might as well see if I can take care of some other stuff too.  May try to figure out branching again after the debacle last time...  o_O

**Comment by calmor15014** [comment]
Branch issue38 created for this issue.  Fix seems relatively benign so I pushed it there.  I'll try to test tonight once I reinstall the mythtv api in my venv. You're welcome to give it a go also and let me know.
